        <footer id="footer">
            <div id="box-logo-c19">
            <img src="img/serjuani.png" alt="logo" id="logo-c19">
            </div>
            <ul id="foot-ul">
                <li><a href="profil.php" class="foot-lien">Profil</a></li>
                <li><a href="salons.php" class="foot-lien">Liste des salons</a></li>
                <li><a href="inscription.php" class="foot-lien">Inscription</a></li>
                <li><a href="connexion.php" class="foot-lien">Connexion</a></li>
                <li><a href="déconnexion" class="foot-lien">Déconnexion</a></li>
            </ul>
        </footer>
    </body>
</html>