        <footer id="footer">
            <img src="" alt="">
            <ul>
                <li><a href="profil.php">Profil</a></li>
                <li><a href="salons.php">Liste des salons</a></li>
                <li><a href="inscription.php">Inscription</a></li>
                <li><a href="connexion.php">Connexion</a></li>
                <li><a href="déconnexion">Déconnexion</a></li>
            </ul>
        </footer>
    </body>
</html>