<!DOCTYPE html>
<html>
<head>
    <meta charset="utf8">
    <link rel="stylesheet" href="css/style.css">
</head>
    <body id="header1-body">
        <div id="header1-backbox">
            <header id="header1-index">
                <div id="div-for-headnav">
                    <nav id="header1-nav">
                        <h1 id="header1-title1"><a id="logoLien" href="index.php">Covidéo-19</a></h1>
                        <ul id="header1-ul">
                            <li><a href="profil.php" class="header1-lien">Profil</a></li>
                            <li><a href="listesalons.php" class="header1-lien">Liste des salons</a></li>
                            <li><a href="inscription.php" class="header1-lien">Inscription</a></li>
                            <li><a href="connexion.php" class="header1-lien">Connexion</a></li>
                            <li><a href="deconnexion.php" class="header1-lien">Déconnexion</a></li>
                        </ul>
                    </nav>
                </div>
            </header>